api_ssh_user: manager
master_controller: 192.168.1.1
api_host: localhost
api_port: 35709
command_timeout_seconds: 10
master_timeout_seconds: 20
feedback: True
feedback_host: localhost
feedback_port: 35711